### PR TITLE
Test Updated Character Groups for XML Schema Regexes for OSCAL Token Data Type

### PR DESCRIPTION
**Pull request by aj-stein-nist**
Test updates in usnistgov/metaschema#183. This closes usnistgov/OSCAL#1127.

# Committer Notes

{Please provide a brief description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please include [WIP] at the beginning of the title or mark the PR as DRAFT.}

### All Submissions:

- [x] Have you selected the correct base branch per  [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you included examples of how to use your new feature(s)?
- [x] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
Updated this to point to `release-1.0` in place of `main` as this is a bug fix we want to land in the 1.0.2 release. @david-waltermire-nist pending usnistgov/metaschema#183, merged (I approved last week), this will be ready to go and/or I can update again to the right submodule commit. LMK, thanks.

**Comment by david-waltermire-nist** [comment]
@david-waltermire-nist Will integrate the data type changes from usnistgov/metaschema#191 to complete this PR.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist, I know you are doing PR review, I assume this one is waaaay out of date. I can bring it up to the current commit if you need or we can close. Either way.

**Comment by aj-stein-nist** [comment]
Per conversation with PR, don't close this. Update to latest metaschema commit once usnistgov/metaschema#199 and usnistgov/metaschema#204.

**Comment by aj-stein-nist** [comment]
@MPemy, if you want I can update this PR accordingly (I agreed to that for the team before I depart today in https://github.com/usnistgov/OSCAL/pull/1161#issuecomment-1101542565) and you can clone my fork of the repo to test? It will be merged into `v1.0.3` once the "final it's ready version of the Metaschema module" is ready and we know the specific commit.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist I know this is a small lift, but I pointed the submodule as metaschema changes have stabilized as it pertains to the OSCAL v1.0.3 release at least up to commit https://github.com/usnistgov/metaschema/commit/86952d7b283c41dcfcfcd68ceb7b7e1e2e289c9b on `master`. We discussed today this should be good enough for upcoming release since any significant Metaschema changes are merged in and good to go. Let me know if you needed changes or prefer I start over.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist ok, haha, just kidding for a second time! Per our convo rebased to metaschema `main` (renamed from `master`) after discussion on the call. I didn't notice you backported `main` changes into `develop`, sorry for the confusion.

**Comment by aj-stein-nist** [comment]
> Any reason this shouldn't be updated to commit 86952d7b283c41dcfcfcd68ceb7b7e1e2e289c9b?

Nope, other then some really PEBKAC nonsense from me apologies. Please see updated force push. 🤦

**Pull request merged**
