### PR TITLE
Fix concept links.

### PR DESCRIPTION
**Pull request by ohsh6o**
# Committer Notes

Fix links.

Closes usnistgov/OSCAL#968.

### All Submissions:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [X] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [X] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by david-waltermire-nist** [comment]
The pages you updated are automatically generated and will get overwritten the next time they are generated. When I merge this PR, I'll update the [base template](https://github.com/usnistgov/OSCAL/blob/main/docs/archetypes/model-reference/_index.md) to include these links in newly generated pages.

**Comment by ohsh6o** [comment]
> The pages you updated are automatically generated and will get overwritten the next time they are generated. When I merge this PR, I'll update the [base template](https://github.com/usnistgov/OSCAL/blob/main/docs/archetypes/model-reference/_index.md) to include these links in newly generated pages.

I guess that explains some things. Is there something I can do to help with how that env var is set for Hugo to operate properly? I thought what you mean here explains all the changes I made here are irrelevant. 🤦 

I only took care of this last week because I stakeholder clicked on them in a meeting and I realized the `href` targets were all empty, so let me know if this PR is useful, but in fact it sounds like it is not.

**Comment by david-waltermire-nist** [comment]
@ohsh6o I am working on a PR to address this in the generated pages. I'll link it as soon as I have something working and tested.

**Comment by ohsh6o** [comment]
OK, cool. I will opt to close this PR and leave the issue open!

**Pull request closed without merging**
