### PR TITLE
Documenting OSCAL usage for Release

### PR DESCRIPTION
**Pull request by david-waltermire-nist**
# Committer Notes

Addressing the README from issue #341.

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?

### CODE REVIEW

**Comment by david-waltermire-nist** [comment]
@brianrufgsa I refactored your readme content from issue #341 into multiple information resources. Please give this a review. I still need to add the information on "Future OSCAL Compatibility Commitment" to the website. The content on "extending OSCAL" is going to get merged into the schema docs.

**Comment by brianrufgsa** [comment]
@david-waltermire-nist Overall this looks great!
Just one issue ... in two places:

- json/README.md, Line 57
- xml/README.md, Line 56  

Both incorrectly have the xmllint URL instead of the Saxon-HE URL. The correct URL is: http://www.saxonica.com/

**Comment by david-waltermire-nist** [comment]
@brianrufgsa I fixed the Saxon link in the latest.

**Comment by wendellpiez** [comment]
Let's put links at the top of both XML and JSON readme docs, to point to the other readme and to make it clear that conversions are supported in both directions. 😎

**Comment by david-waltermire-nist** [comment]
I fixed @iMichaela review issues and @brianrufgsa reviewed these.

**Pull request merged**
