### PR TITLE
1929 update markdown link

### LINKED ISSUE #1926: Scheduled Check of Markdown Documents Found Bad Hyperlinks
FILE: .github/ABOUT.md
  [✓] ISSUE_TEMPLATE/
  [✓] workflows
  [✓] CODEOWNERS
  [✓] issue_template.md

  4 links checked.

FILE: .github/ISSUE_TEMPLATE/README.md
  [✓] bug_report.yaml
  [✓] question.yaml
  [✓] feature_request.yaml

  3 links checked.

FILE: .github/PULL_REQUEST_TEMPLATE.md
  [✓] https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md
  [/] https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
  [✓] https://github.com/usnistgov/OSCAL/pulls
  [✓] https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
  [✓] https://creativecommons.org/publicdomain/zero/1.0/
  [✓] https://github.com/usnistgov/OSCAL/wiki/Issue-Review
  [✓] https://pages.nist.gov/OSCAL

  7 links checked.

FILE: .github/issue_template.md
  No hyperlinks found!

  0 links checked.

FILE: CODE_OF_CONDUCT.md
  [✓] mailto:oscal@nist.gov
  [✓] http://contributor-covenant.org
  [✓] http://contributor-covenant.org/version/1/4/

  3 links checked.

FILE: CONTRIBUTING.md
  [✓] #overview
  [✓] #project-approach
  [✓] #contribution-options
  [✓] #issue-reporting-triage-and-handling
  [✓] #communications-mechanisms
  [✓] #contributing-to-the-repository
  [✓] #repository-structure
  [✓] #contributing-to-a-development-sprint
  [✓] #user-stories
  [✓] #issue-status
  [✓] #reporting-issue-progress
  [✓] #git-repo-checkout
  [✓] #initializing-git-submodules
  [✓] #configuring-submodules-to-use-ssh
  [✓] #updating-submodules
  [✓] #licenses-and-attribution
  [✓] #this-project-is-in-the-public-domain
  [✓] #contributions-will-be-released-into-the-public-domain
  [✓] https://github.com/orgs/usnistgov/projects/25
  [✓] https://pages.nist.gov/OSCAL/about/projects/
  [✓] https://opensource.guide/how-to-contribute/
  [✓] https://github.com/usnistgov/OSCAL/issues
  [/] https://help.github.com/articles/creating-an-issue/
  [✓] https://github.com/usnistgov/OSCAL/issues/new?template=feature_request.md&labels=enhancement%2C+User+Story
  [✓] https://github.com/usnistgov/OSCAL/issues/new?template=bug_report.md&labels=bug
  [✓] https://github.com/usnistgov/OSCAL/issues/new?labels=question&template=question.md
  [✓] https://github.com/usnistgov/OSCAL/projects/52
  [✓] mailto:oscal-dev@nist.gov
  [✓] mailto:oscal-dev+subscribe@list.nist.gov
  [✓] mailto:oscal-dev+unsubscribe@list.nist.gov
  [✓] mailto:oscal-updates@list.nist.gov
  [✓] mailto:oscal-updates+subscribe@list.nist.gov
  [✓] mailto:oscal-updates+unsubscribe@list.nist.gov
  [✓] https://github.com/usnistgov/OSCAL/releases
  [✓] versioning-and-branching.md
  [/] https://guides.github.com/introduction/flow/
  [/] https://help.github.com/articles/fork-a-repo/
  [/] https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/
  [/] https://help.github.com/articles/creating-a-pull-request-from-a-fork/
  [/] https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
  [✓] ./versioning-and-branching.md
  [/] https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request
  [✓] .github
  [✓] build
  [✓] src
  [✓] https://github.com/usnistgov/oscal-content/tree/main/src
  [✓] CODE_OF_CONDUCT.md
  [✓] CONTRIBUTING.md
  [✓] LICENSE.md
  [✓] USERS.md
  [✓] https://github.com/usnistgov/OSCAL/issues?q=is%3Aopen+is%3Aissue+label%3A%22User+Story%22
  [✓] https://github.com/usnistgov/OSCAL/issues/new?labels=User+Story%2C+enhancement&template=feature_request.md
  [✓] https://creativecommons.org/publicdomain/zero/1.0/

  53 links checked.

FILE: LICENSE.md
  [✓] #this-project-is-in-the-worldwide-public-domain
  [✓] #fair-use-of-nist-dataworks
  [✓] #nist-software
  [✓] #contributions-to-this-project
  [✓] https://creativecommons.org/publicdomain/zero/1.0/
  [✓] https://www.nist.gov/open/license
  [✓] CONTRIBUTING.md

  7 links checked.

FILE: README.md
  [✓] https://gitter.im/usnistgov-OSCAL/Lobby
  [✓] https://github.com/usnistgov/OSCAL/actions/workflows/status.yml
  [✓] https://github.com/usnistgov/OSCAL/releases
  [✓] https://csrc.nist.gov/Projects/Open-Security-Controls-Assessment-Language
  [✓] https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md
  [✓] https://www.nist.gov/oscal
  [✓] https://pages.nist.gov/OSCAL/reference/
  [✓] https://pages.nist.gov/OSCAL/concepts/examples/
  [✓] https://github.com/usnistgov/OSCAL/
  [✓] https://github.com/usnistgov/OSCAL-Pages/
  [✓] https://github.com/usnistgov/OSCAL-Reference/
  [✓] https://github.com/usnistgov/oscal-content/
  [✓] https://github.com/usnistgov/OSCAL-DEFINE/
  [✓] https://github.com/usnistgov/OSCAL/releases
  [✓] mailto:oscal@nist.gov
  [✓] https://github.com/usnistgov/OSCAL/issues
  [✓] https://pages.nist.gov/OSCAL/contribute/
  [✓] https://www.nist.gov/blogs/cybersecurity-insights/foundation-interoperable-and-portable-security-automation-revealed
  [✓] https://pages.nist.gov/OSCAL/
  [✓] https://github.com/usnistgov/oscal-content/tree/main/nist.gov/SP800-53/rev5
  [✓] https://github.com/usnistgov/oscal-content/tree/main/nist.gov/SP800-53/rev4
  [✓] https://github.com/GSA/fedramp-automation/tree/master/dist/content/rev4/baselines
  [✓] mailto:oscal-dev@list.nist.gov
  [✓] https://pages.nist.gov/OSCAL/contact/
  [✓] https://img.shields.io/gitter/room/usnistgov-OSCAL/Lobby
  [✓] https://github.com/usnistgov/OSCAL/actions/workflows/status.yml/badge.svg
  [✓] https://img.shields.io/github/v/release/usnistgov/OSCAL?color=green

  27 links checked.

FILE: README_validations.md
  [✓] https://pages.nist.gov/OSCAL/concepts/layer/validation/
  [✓] https://github.com/usnistgov/OSCAL/releases/latest/
  [✓] ./build/README.md
  [✓] https://pages.nist.gov/OSCAL/concepts/layer/#status-of-the-oscal-layers
  [✓] https://www.w3.org/TR/xmlschema-1/
  [✓] https://json-schema.org/
  [✓] https://linux.die.net/man/1/xmllint/
  [✓] https://github.com/ajv-validator/ajv-cli
  [✓] ./versioning-and-branching.md
  [✓] https://github.com/usnistgov/metaschema/

  10 links checked.

FILE: USERS.md
  No hyperlinks found!

  0 links checked.

FILE: build/README.md
  [✓] https://maven.apache.org/
  [✓] https://nodejs.org/en
  [✓] ./.nvmrc
  [✓] https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home
  [✓] https://git-scm.com/
  [✓] https://www.gnu.org/software/make/
  [✓] https://infozip.sourceforge.net/
  [✓] https://git.savannah.gnu.org/cgit/bash.git/tree/NEWS?h=bash-3.2-beta
  [✓] ./Makefile
  [✓] https://github.com/usnistgov/OSCAL/discussions/1852
  [✓] ../.github/workflows/release.yml
  [✓] ../src/utils/resolver-pipeline/
  [✓] #archive-generation
  [✓] https://json-schema.org/specification-links.html#draft-7
  [✓] https://www.w3.org/TR/xmlschema11-1/
  [✓] https://pages.nist.gov/OSCAL/documentation/schema/
  [✓] https://github.com/usnistgov/OSCAL/releases
  [✓] https://ajv.js.org/
  [✓] https://github.com/jessedc/ajv-cli
  [✓] https://github.com/usnistgov/oscal-content
  [✓] https://github.com/jessedc/ajv-cli#installation
  [✓] https://nodejs.org/en/download/current/
  [✓] http://xmlsoft.org/xmllint.html
  [✓] http://xmlsoft.org/downloads.html
  [✓] https://www.w3.org/TR/xslt-30/
  [✓] https://www.w3.org/TR/xpath-31/
  [✓] http://saxon.sourceforge.net/
  [✓] http://saxon.sourceforge.net/#F9.9HE
  [✓] https://search.maven.org/artifact/net.sf.saxon/Saxon-HE
  [✓] http://www.saxonica.com
  [✓] https://www.w3.org/TR/xpath-functions-31/#func-json-to-xml

  31 links checked.

FILE: decisions/0001-record-architecture-decisions.md
  [✓] http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions

  1 links checked.

FILE: decisions/0002-communicating-nist-oscal-events-to-the-public.md
  [✓] #service-account-with-published-nist-office-365-calendar
  [✓] https://en.wikipedia.org/wiki/ICalendar
  [✓] https://pages.nist.gov/OSCAL/contact/#oscal-mailing-lists
  [✓] mailto:oscal-dev@list.nist.gov
  [✓] https://github.com/usnistgov/OSCAL/pull/1614
  [✓] https://csrc.nist.gov/Events
  [✓] #cms-for-the-nist-computer-security-resource-center-website-and-calendar
  [✓] https://www.nist.gov/news-events/events/calendar
  [✓] https://www.nist.gov
  [✓] mailto:oscalevt@nist.gov

  10 links checked.

FILE: decisions/0003-github-labels-decluttering.md
  [✓] https://github.com/usnistgov/OSCAL/issues/1496
  [✓] https://hackmd.io/UrSjUKGiQRuiA2VJLG-Mpg

  2 links checked.

FILE: decisions/0004-issue-triage.md
  [✓] https://github.com/usnistgov/OSCAL/blob/60918cd3fc5508b69b71e8691b071108dab46ec9/.github/workflows/issue-triage.yml
  [✓] https://github.com/usnistgov/OSCAL/projects/52
  [✓] https://github.com/orgs/usnistgov/projects/25/
  [✓] https://www.scrum.org/resources/blog/product-backlog-refinement-explained-13

  4 links checked.

FILE: decisions/0005-repository-reorganization.md
  [✓] https://github.com/usnistgov/OSCAL/issues/1802
  [✓] https://github.com/usnistgov/OSCAL-Pages
  [✓] https://github.com/usnistgov/OSCAL-Reference
  [✓] https://pages.nist.gov/OSCAL-Reference
  [✓] https://pages.nist.gov/OSCAL
  [✓] https://github.com/usnistgov/OSCAL/releases/tag/v1.0.6

  6 links checked.

FILE: decisions/0006-source-metaschema-xxes.md
  [✓] https://github.com/usnistgov/OSCAL/issues/1665
  [✓] ./0005-repository-reorganization.md#streamlined-build-process

  2 links checked.

FILE: decisions/adr_template.md
  No hyperlinks found!

  0 links checked.

FILE: src/file-naming-conventions.md
  [✓] #oscal-file-naming-conventions
  [✓] #table-of-contents
  [✓] #naming-oscal-catalog-and-profile-files
  [✓] #catalog-example
  [✓] #profile-examples
  [✓] #naming-oscal-schema-files
  [✓] #schema-examples
  [✓] #naming-oscal-conversion-xsl-templates
  [✓] #conversion-xslt-example
  [✓] https://semver.org/

  10 links checked.

FILE: src/metaschema/doc-identity-notes.md
  No hyperlinks found!

  0 links checked.

FILE: src/metaschema/readme.md
  [✓] https://pages.nist.gov/OSCAL/docs/schemas/
  [✓] https://pages.nist.gov/OSCAL
  [✓] https://pages.nist.gov/metaschema/

  3 links checked.

FILE: src/release/content-upgrade/README.md
  [✓] https://github.com/usnistgov/OSCAL/releases/tag/v1.0.0-milestone1
  [✓] https://github.com/usnistgov/OSCAL/releases/tag/v1.0.0-milestone2
  [✓] https://github.com/usnistgov/OSCAL/releases/tag/v1.0.0-milestone3
  [✓] https://github.com/usnistgov/OSCAL/releases/tag/v1.0.0-rc1
  [✓] https://github.com/usnistgov/OSCAL/releases/tag/v1.0.0-rc2
  [✓] https://github.com/usnistgov/OSCAL/releases/tag/v1.0.0
  [✓] https://www.oracle.com/java/technologies/downloads/
  [✓] http://saxon.sourceforge.net/
  [✓] https://www.w3.org/TR/xslt-30/
  [✓] https://www.oxygenxml.com/
  [✓] https://www.oxygenxml.com/doc/ug-oxygen/topics/xslt-tab.html
  [✓] https://pages.nist.gov/OSCAL/contact/
  [✓] https://www.oxygenxml.com/doc/ug-editor/topics/xslt-stylesheet-parameters.html
  [✓] ../../../build/README.md#converters

  14 links checked.

FILE: src/release/release-notes.md
  [✓] https://github.com/usnistgov/OSCAL/releases

  1 links checked.

FILE: src/specifications/profile-resolution/readme.md
  [✖] https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/
  [✓] https://gitter.im/usnistgov-OSCAL/Lobby
  [✓] https://pages.nist.gov/OSCAL/contact/

  3 links checked.
  [✖] https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/ → Status: 404

FILE: src/utils/readme.md
  [✓] https://pages.nist.gov/OSCAL/tools/
  [✓] https://github.com/usnistgov/oscal-tools

  2 links checked.

FILE: src/utils/resolver-pipeline/TESTING.md
  [✓] ../../specifications/profile-resolution

  1 links checked.

FILE: src/utils/schematron/readme.md
  [✓] oscal-profile.sch

  1 links checked.

FILE: versioning-and-branching.md
  [✓] #versioning
  [✓] #branching
  [✓] #versioning-and-branching
  [✓] #git-setup
  [✓] #branching-for-contributors
  [✓] #personal-working-branches
  [✓] #branching-for-repository-maintainers
  [✓] #release-branches
  [✓] #creating-a-release-branch
  [✓] #releasing-a-release-branch
  [✓] #releasing-a-patch-revision
  [✓] #feature-branches
  [✓] #creating-a-feature-branch
  [✓] #syncing-a-feature-branch-with-develop
  [✓] #merging-a-feature-branch
  [✓] https://semver.org/spec/v2.0.0.html
  [✓] https://github.com/usnistgov/OSCAL/releases
  [✓] https://github.com/usnistgov/OSCAL/tree/main
  [✓] https://github.com/usnistgov/OSCAL/tree/develop
  [✓] ./CONTRIBUTING.md#contributing-to-the-repository
  [✓] https://github.com/usnistgov/OSCAL/tree/nist-pages

  21 links checked.

### PR DESCRIPTION
**Pull request by Arminta-Jenkins-NIST**
# Committer Notes

Updates links in the `src/specifications/profile-resolution/readme.md`. Closes #1926.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- ~Do all automated CI/CD checks pass?~ (Will follow up see https://github.com/usnistgov/OSCAL/issues/1926#issuecomment-1722607532 for unrelated issue but still from link checking.)

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.~

### CODE REVIEW

**Review by aj-stein-nist — APPROVED** [review]
Looks good to me, thanks for taking care of this.

**Comment by aj-stein-nist** [comment]
@Arminta-Jenkins-NIST, I can tell the xmllint.net failure is an ephemeral one in this failed build, but as a learning experience, can you go to [the failed build](https://github.com/usnistgov/OSCAL/actions/runs/6201037241/job/16836911847?pr=1929) and click re-run job to test that? This transient error has happened with this domain in the past. If it does not go green this time, I will merge anyway (it happens every few months), but you corrected what you need. I will just note it in the checklist. Thanks.

**Review by wendellpiez — APPROVED** [review]
LGTM

**Comment by aj-stein-nist** [comment]
> @Arminta-Jenkins-NIST, I can tell the xmllint.net failure is an ephemeral one in this failed build, but as a learning experience, can you go to [the failed build](https://github.com/usnistgov/OSCAL/actions/runs/6201037241/job/16836911847?pr=1929) and click re-run job to test that? This transient error has happened with this domain in the past. If it does not go green this time, I will merge anyway (it happens every few months), but you corrected what you need. I will just note it in the checklist. Thanks.

If you hadn't done it yet, Arminta, you can disregard. An updated link checker pass this evening confirms there is some issue with the GH infrastructure and xmllint.net and the linux.die.net manual page mirror sites too (ironically enough): https://github.com/usnistgov/OSCAL/issues/1926#issuecomment-1722607532. I will merge this now to stop some of the issues and open a new issue to suppress checks for those domains tomorrow if it keeps happening.

**Pull request merged**
