### PR TITLE
Website release page

### PR DESCRIPTION
**Pull request by david-waltermire-nist**
# Committer Notes

Updating website contents to add content about releases. Also reorganizing some content to make the navigation and individual page contents more consistent.

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?

### CODE REVIEW

**Comment by wendellpiez** [comment]
We probably need a sidenav on "Downloads" page for visual consistency with other pages.

I can help to polish the copy, as well.

**Comment by david-waltermire-nist** [comment]
Here is a ["built" version](https://github.com/usnistgov/OSCAL/files/3287045/OSCAL.zip) of the draft site to run in a local webserver.

**Comment by brianrufgsa** [comment]
@david-waltermire-nist Once again, this looks great overall!
Below are a few notes:
- For the framework links, consider having them open in a new page/tab.
- Even though it's just examples, we should add CSA to that list since they are an interested party.
- In general, we use active voice and present tense. One exception: Under "Why OSCAL?, last paragraph: change "... OSCAL will reduce ..." to "... OSCAL reduces ..." (fix the tense in the remainder of the sentence: "decreases", "enables")
- Under "Why OSCAL?", last paragraph. Three line sentence. Consider breaking up. Also, you are using commas to break up a list, but also using a comma within the last element of the list. Consider using semi-colons or bullets to break up the list or restructure sentence to avoid this construct.
- For each of the four roles, under "How Does OSCAL Help Me?", the bullets are sentence fragments. If you are going to keep the fragments, drop the periods. (rule of thumb - complete sentences have periods - phrases/fragments do not) Alternatively, consider making it grammatically complete and correct as follows: Add a lead in line that simply says, "OSCAL:", then start each line in lower case, and end each line with a semicolon, except for the second to last line, which ends with "; and", and the last line, which ends with a period.  (for the Tool Developer bullets, the re-work isn't as straight-forward.)
- Under "Tool Developers" second bullet. Neither tool developers nor tools should be "attest[ing]" to the state of anything. Tools might enable system owners or auditors to "attest". 
- Consider leaving the links for the four roles in the side menu on the pages with the role-specific content. It's more user friendly than having to go back a page before I can click to see the next user role description.
- Under Security Professionals, third bullet, consider "reduced" instead of "less".
- Under Tool Developers, first sentence. Add a comma after "... [eGRC] systems)". The first "or" indicates the start of a new idea. The second "or" links two possibilities within that idea, thus only use the comma before the first "or".
- Under Tool Developers, second paragraph. Tool development can extend to assessment activities and reporting as well. This stops at implementation.
- Under "Challenges Addressed", first sentence. Drop "is attempting to". Use "OSCAL addresses ..."
- Under "Challenges Addressed", second to last paragraph. The PCI reference is a paren in a paren. Change the inner parens to brackets.
- Under "Challenges Addressed", last paragraph on page, second to last sentence. Chane "OSCAL information **can be** interoperable" to "OSCAL information **is** interoperable"
- Under OSCAL Design Principles, first sub-bullet includes, "improve the Machine Experience (MX)". Seems like random placement. Perhaps it was intended to be a separate bullet.
- Under Case Studies/ FedRAMP:
   - You spell out GSA, and then cite FedRAMP by acronym only. Suggest title should be, "General Services Administration (GSA) Federal Risk and Authorization Management Program (FedRAMP)".
   - In the first sentence, change "approved" to "authorized".
  - In the second sentence, insert "(NIST)" and "(OSCAL)" next to those spelled-out names.
  - Matt is no longer the director. He was at that time. 
  - Spell out ATARC acronym. (Advanced Technology Academic Research Center)
  - Second paragraph, OSCAL does NOT automate FedRAMP's assessments. It enables assessment automation.
 - Consider dropping the 4th and 5th paragraphs. FedRAMP Tailored is not relevant. It was a coincidental announcement.
- Under "Scenarios", SSPs, it hasn't been C&A for several years. It's "A&A" now.  (Assessment and Authorization). Regardless, the close-paren should be after the A, not after the word "process".

**Comment by david-waltermire-nist** [comment]
[Here](https://github.com/usnistgov/OSCAL/files/3293443/OSCAL-site-20190615.zip) is the latest site with all comments addressed.

@iMichaela Please provide comments providing any specific changes you still want.

**Pull request merged**
