### PR TITLE
Added OSCAL-deep-diff content to docs

### PR DESCRIPTION
**Pull request by nikitawootten-nist**
# Committer Notes

Added OSCAL-deep-diff to the tools page, and the recent lunch with the devs presentation to the presentation page.

Note the base branch is not set to `develop` as the contributing doc suggests, since `develop` is currently significantly out of date on the `tools` page, and would cause merge conflicts down the line.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Review by aj-stein-nist — APPROVED** [review]
LGTM

**Review by david-waltermire-nist — APPROVED** [review]
LGTM. Thanks!

**Review by iMichaela — COMMENTED** [review]
Please see the comment regarding the placement of the new information in the table. Other than that, the information is accurate.

**Comment by david-waltermire-nist** [comment]
@iMichaela The tools on the tools page are listed alphabetically. The events page is listed in reverse chronological order. I believe the placement for these items is correct, given the above. I'll add notes to these pages about the ordering.

**Comment by iMichaela** [comment]
@david-waltermire-nist - I realized that about the events page. I like the alphabetical listing approach. We did not have it before and did not realize it has been implemented. Sorry. Just wanted to be fair to everyone.

**Pull request merged**
