### PR TITLE
added new Angular project to begin addressing issue #606

### PR DESCRIPTION
**Pull request by mocolicious**
# Committer Notes

{Please provide a brief description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please include [WIP] at the beginning of the title or mark the PR as DRAFT.}

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by secautobuilder** [comment]
@mocolicious Thanks for starting this. What is this application intended to do?

Also, we are keeping tooling in separate repos. Can you create a new repo and post the tool there? Once you have something working, we can provide a link to your repo on our tools page.

**Comment by mocolicious** [comment]
@secautobuilder its intended to address the open issue #606 created by @justKuzya to create dev environment using Angular.

**Comment by bradh** [comment]
I wonder if this would be better in a different repo (e.g. as a submodule, or a peer of OSCAL).

**Comment by mocolicious** [comment]
@bradh I created a new repo at https://github.com/mocolicious/OSCAL-Examples

**Pull request closed without merging**
