### PR TITLE
Add CVSS v4 Facet Support

### PR DESCRIPTION
**Pull request by david-waltermire**
# Committer Notes

This PR adds constraints for assessment results facets for [CVSS v4.0](https://www.first.org/cvss/v4-0/).

The names and values used are the initialisms used in the CVSS vector string, to provide for a more concise representation that aligns with how CVSS is commonly used in many tools.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by aj-stein-gsa** [comment]
@david-waltermire, as this PR is not strictly a bug fix but is still backwards compatible, if you would like to target this PR at the `main` branch and propose I include it in the https://github.com/usnistgov/OSCAL/discussions/2072, please let me know.

**Comment by david-waltermire** [comment]
This is a new enhancement, so I am comfortable with this being considered for the next minor release, as long as that is not too far into the future, since some organizations are already adopting CVSS 4.0.

**Comment by iMichaela** [comment]
@david-waltermire - I reviewed the proposed support for the CVSS 4.0. 
I noted that CVSS v3.1 Facet is supported as a stand alone facet but there are no constraints associated with it nor it appears to be added to the CVSS v3.0 constraints. Do you mind ensuring no more updates are necessary for the CVSS support.

**Review by iMichaela — APPROVED** [review]
Proposed support for CVSS 4.0 looks good.

**Comment by iMichaela** [comment]
@david-waltermire - Can you please rebase your branch. I am not able to do so on your behalf.

**Comment by david-waltermire** [comment]
> @david-waltermire - I reviewed the proposed support for the CVSS 4.0. I noted that CVSS v3.1 Facet is supported as a stand alone facet but there are no constraints associated with it nor it appears to be added to the CVSS v3.0 constraints. Do you mind ensuring no more updates are necessary for the CVSS support.

The facets for 3.0 and 3.1 are the same (minus the system), so the constraints for the values are shared between the two. This is because v3.0 and v3.1 only focused on adjusting guidance around how to apply the scoring system. See the following examples.

https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_assessment-common_metaschema.xml#L1498

https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_assessment-common_metaschema.xml#L1522

https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_assessment-common_metaschema.xml#L1532

**Comment by david-waltermire** [comment]
> @david-waltermire - Can you please rebase your branch. I am not able to do so on your behalf.

On what branch should I rebase? 

FWIW, I have marked my PR as editable by maintainers as required in the PR template, so you should be able to rebase on you own.

**Comment by iMichaela** [comment]
> > @david-waltermire - Can you please rebase your branch. I am not able to do so on your behalf.
> 
> On what branch should I rebase?
> 
> FWIW, I have marked my PR as editable by maintainers as required in the PR template, so you should be able to rebase on you own.

image

There are conflicts I need to address manually. I can do so locally by pulling your branch and merge it into develop, but I want to ensure the correct selection is made when conflicts are addressed, unless you can address them and push them to the PR.

**Comment by david-waltermire** [comment]
It looks like you created some merge commits that where we causing the problem. I'd recommend generally using `git rebase` instead of `git merge` to prevent this.

I rebased using `git pull -r origin develop` and it is back to a clean, single commit PR.

**Comment by iMichaela** [comment]
> It looks like you created some merge commits that where we causing the problem. I'd recommend generally using `git rebase` instead of `git merge` to prevent this. This can dramatically reduce the number of merge conflicts.
> 
> I rebased using `git pull -r origin develop` and it is back to a clean, single commit PR.

Thank you!

**Pull request merged**
