### PR TITLE
Addressing issues #696 and #698

### PR DESCRIPTION
**Pull request by david-waltermire-nist**
# Committer Notes

Updated readme to remove missing architecture diagram and to include milestone 3 info. (#696)
Also added the component example to the CI/CD. (#698)

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by david-waltermire-nist** [comment]
This PR is ready to review.

**Comment by iMichaela** [comment]
@david-waltermire-nist - Everything looks good to me. The only thing I would add to the modified README.md would be some information regarding the preferred way of providing feedback. In the sentence:  "We will continue to collect feedback from the community on the OSCAL models. [HERE] We are also seeking ..." where [HERE] can be: "The preferred feedback method would be via GitHub issues using our template. Alternatively, if the reviewer does not have access to GitHub, an email to oscal@nist.gov describing the issue can be used to convey the information to our team and we will create the issue on your behalf." I leave it up to you to decide.

**Comment by david-waltermire-nist** [comment]
The last two sentences in that paragraph instruct the reader to send private feedback to oscal@nist.gov and public feedback to oscal-dev@list.nist.gov. I don't think we need to say the same thing again in the same paragraph. Further, the contact info is provided twice more at the end of the readme. It might make sense to clean this up to reduce the repetition some. I think this can be done in a later PR.

**Comment by iMichaela** [comment]
I wrongly assumed you prefer the OSCAL models' feedback as GitHub issues. If this is not the case, then please disregard the comment. I concur with you regarding the cleanup - having the information in one place and provide pointers to that place when/if needed provides easier maintenance too.

**Comment by david-waltermire-nist** [comment]
I do have a preference for GitHub issues, but I would rather get an email vs no feedback. We can take the feedback by email for now and ask for more complicated issues that the sender post it on GitHub. I think this is a good compromise.

Dave

**Comment by iMichaela** [comment]
I agree. This is exactly what my suggestion was based on - your preference for GitHub and the possibility of having reviewers that prefer a different feedback method. Again - that was a simple suggestion knowing your preferences. No need to spend so much time on messaging on this topic. I reviewed the PR, as requested, and already approved it - no changes requested (only a suggestion).

**Pull request merged**
