### PR TITLE
Codegen

### PR DESCRIPTION
**Pull request by RS-Credentive**
# Committer Notes

This PR updates the names of some of the datatypes with the latest metaschema datatype names. This change is necessary for the metaschema XML files to be properly validated against metaschema.xsd

### All Submissions:

- [X] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [X] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Review by RS-Credentive — COMMENTED** [review]
Michaela, as requested - my PR is rebased against develop

**Comment by iMichaela** [comment]
> Michaela, as requested - my PR is rebased against develop

Thank you. It looks good now. I'll work on it today (test/approve)

**Review by iMichaela — COMMENTED** [review]
This PR updates OSCAL to the Metaschema's latest "date-time-with-timezone" datatype. NIST is ready to merge it into `develop` and include it in the new (1.1.3) patch release should it NOT impact negatively FedRAMP or other community adopters.

**Comment by iMichaela** [comment]
[TIME SENSITIVE]: The community's feedback is highly encouraged.

**Review by david-waltermire — APPROVED** [review]
This should not break backwards compatibility as these types have long been supported in the XSLT and Java implementations.

**Review by iMichaela — APPROVED** [review]
LGTM. Thank you, @RS-Credentive

**Pull request merged**
