### PR TITLE
Docs redesign

### PR DESCRIPTION
**Pull request by anweiss**
# Committer Notes

This is the main PR with all of the aggregated changes to and redesigned elements of the OSCAL documentation. Courtesy of @wendellpiez and @howieavp76.

*NOTE*: This content is still a work in progress and should not be merged until given the green light by @iMichaela and @david-waltermire-nist.

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you written new tests for your core changes, as applicable?
* [X] Have you included examples of how to use your new feature(s)?

### CODE REVIEW

**Comment by anweiss** [comment]
@wendellpiez @howieavp76 we now have a clean, squashed and rebased branch and PR for `docs-redesign` ... I recommend deleting your local `docs-redesign` and re-fetching as follows:

    $ git checkout master
    $ git branch -D docs-redesign
    $ git checkout -b docs-redesign anweiss/docs-redesign

This should make things a lot cleaner to work with. Please ensure that any tertiary features that you're working to support docs (e.g. metaschema changes for auto generation, etc) _only contain commits with those features_. If you auto generate content from your tertiary branch(s), only commit that generated content into your local `docs-redesign` branch and not into your tertiary feature branch. This will make it cleaner when it comes time to rebase into `docs-redesign`.

**Comment by david-waltermire-nist** [comment]
This also relates to isssue #286.

**Comment by anweiss** [comment]
@david-waltermire-nist @wendellpiez taking this out of draft status and gearing it up for review. This branch has already been cleanly rebased on to `usnistgov/master` which should make this a simple squash and merge when ready.

**Comment by david-waltermire-nist** [comment]
Ok. I'll give it a final review today and then merge.

**Pull request merged**
