### PR TITLE
Correct issues on events page

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

Correct typo and fix links for #1711.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
Final merge and publication blocked by #1698 but still good to go and review regardless in the interim.

**Review by nikitawootten-nist — APPROVED** [review]
Simple PRs are the best, LGTM

**Comment by aj-stein-nist** [comment]
> Simple PRs are the best, LGTM

Thanks, we still need to handle CI/CD problems in another issue before merged.

**Review by wendellpiez — APPROVED** [review]
LGTM as well

**Comment by aj-stein-nist** [comment]
I am going to merge this to test in conjunction with #1721. If the pages don't deploy I will be forced to work through it.

**Comment by aj-stein-nist** [comment]
What a surprise, it didn't work. Away we go, more debugging to come and notes.

**Pull request merged**
