### PR TITLE
Adds Ramper to OSCAL tools list

### PR DESCRIPTION
**Pull request by hahsan-ti**
# Committer Notes

The PR adds Ramper description to the list of tools that support OSCAL.

### All Submissions:

- [X] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [X] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [X] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [X] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Review by iMichaela — CHANGES_REQUESTED** [review]
@hahsanti - Ramper's description indicates that the tool can generate a 'continuous monitoring package using OSCAL 1.0.0', while the general description only lists POA&Ms generation (there is no OSCAL model for Deviation Requests). It would be useful for the readers to better understand what OSCAL other models are supported and what type of OSCAL content Ramper is able to generate. The Ramper.io website says nothing about OSCAL, so I could not obtain any additional information there per the description statement. Please clarify in the tool's description what OSCAL content can be generated, so OSCAL users gain a better understanding of Ramper's benefits to them. Thank you.

**Review by david-waltermire-nist — CHANGES_REQUESTED** [review]
Per the comment from @iMichaela, please clarify in the tool's description what OSCAL content can be generated, so OSCAL users gain a better understanding of Ramper's benefits to them.

**Review by david-waltermire-nist — APPROVED** [review]

**Review by david-waltermire-nist — CHANGES_REQUESTED** [review]
Per the comment from @iMichaela, please clarify in the tool's description what OSCAL content can be generated, so OSCAL users gain a better understanding of Ramper's benefits to them.

**Comment by david-waltermire-nist** [comment]
@hahsan-ti We welcome this listing, but it's been 5 months with no response on this PR. I am going to close the PR. We can reopen it if you address the changes we requested.

**Comment by hahsan-ti** [comment]
Hi. Does this repo still maintain a list of tools that support OSCAL?

**Comment by iMichaela** [comment]
@hahsan-ti - NIST is only maintain a list of the tools NIST develops. The community maintains a more comprehensive list. Please visit [Awesome OSCAL](https://github.com/oscal-club/awesome-oscal) or [OSCAL.io](https://oscal.io/)

**Pull request closed without merging**
