### PR TITLE
Added artifact usage + corrected dead links

### PR DESCRIPTION
**Pull request by nikitawootten-nist**
# Committer Notes

- Added usage instructions for JSON Schema, XSD, and converter artifacts.
- Corrected dead links
- Small adjustment to the versioning and branching document

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you included examples of how to use your new feature(s)?
- [x] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Review by JustKuzya — DISMISSED** [review]
Seems like a lot of simple changes, though I'm not sure if link validator can validate  ./ and ../../../ paths. Can it?

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist should this PR target `main` and then be pushed to `develop` or the other way around?

I assume we will make all changes and prep for a release (so `develop`-> release tag -> `main`), so `develop` now we don't have the site content in here, correct?

**Comment by aj-stein-nist** [comment]
> Seems like a lot of simple changes, though I'm not sure if link validator can validate ./ and ../../../ paths. Can it?

Pull down the branch, go into the `build` directory and run link checking like so. (But this is also run by the CI/CD, but if you want to know how to validate yourself): `git checkout remotename branch; pushd build; make linkcheck; popd;`.

**Review by aj-stein-nist — APPROVED** [review]

**Review by aj-stein-nist — CHANGES_REQUESTED** [review]
Wait hold up, I am glad Dmitry asked there is some issue with how linkcheck is run locally and it fails, is it the same in CI/CD?

**Comment by nikitawootten-nist** [comment]
Yeah I'm getting a traceback:
```
/Users/naw2/Documents/repos/oscal/OSCAL/build/node_modules/async/dist/async.js:324
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /Users/naw2/Documents/repos/oscal/OSCAL/build/node_modules/async/dist/async.js:324:36
    at /Users/naw2/Documents/repos/oscal/OSCAL/build/node_modules/async/dist/async.js:248:17
    at /Users/naw2/Documents/repos/oscal/OSCAL/build/node_modules/markdown-link-check/index.js:129:13
    at /Users/naw2/Documents/repos/oscal/OSCAL/build/node_modules/link-check/lib/proto/http.js:117:21
    at done (/Users/naw2/Documents/repos/oscal/OSCAL/build/node_modules/needle/lib/needle.js:463:14)
    at PassThrough.<anonymous> (/Users/naw2/Documents/repos/oscal/OSCAL/build/node_modules/needle/lib/needle.js:717:9)
    at PassThrough.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.3.1
make: *** [Makefile:125: generated/mlc_report.log] Error 1
```

But this doesn't happen in CI? Weird

**Review by aj-stein-nist — APPROVED** [review]
OK, I apologize. I had not properly pulled down the correct updated branch locally as I was replying to @JustKuzya. 🤦 This is good and valid, I go back to approving (it's a little slower locally than I recalled).

**Comment by aj-stein-nist** [comment]
> Yeah I'm getting a traceback:
> ... 
> But this doesn't happen in CI? Weird

I only get that when link check fails, but on clean branches I don't get the stack trace, weird to me too. I guess we can review and reconsider the issue, reassessing markdown-link-checker if we'd like.

**Pull request merged**
