### PR TITLE
Publish Official Container Image for Developers

### PR DESCRIPTION
**Pull request by xee5ch**
# Committer Notes

This implements a GitHub Actions workflow to deploy a container of the OSCAL CLI tools. This closes usnistgov/OSCAL#1008.

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by xee5ch** [comment]
@david-waltermire-nist, I think this is ready for review now. I had to fix a couple of nits. The image is still quite large, but most of it is the `/usr` directory all the installed Debian packages that were needed.

If you want to see this in action, you can see I set it up in [the OSCAL Club test organization](https://github.com/oscal-club/OSCAL/pkgs/container/oscal%2Fcli) and it works a treat. I did this with the GitHub Container Registry because of [practical limitations on use of Docker with regards to public rate limiting unless you have a paid-for account](https://www.docker.com/increase-rate-limits). I am willing to make a separate issue to investigate how to securely sync a copy to Docker Hub as well, if the NIST OSCAL and community developers agree, it is so popular we ought to put a copy there as well.

Also worth calling out, and I am definitely willing to talk about this in a developer session as to why: I have built the image with `buildah` and use it locally with `podman`. The former allows ["rootless" and "daemonless" building of the container, which is far more secure for those who would need to locally modify builds and test the containers on their own workstations](https://developers.redhat.com/blog/2020/09/25/rootless-containers-with-podman-the-basics). Nonetheless, you can still use `docker` and `docker-compose`. For that reason, I also added back a user, `oscal`, such that people running do not run with root privileges in the container by default (they can override it), and limit blast radius from the occasional container breakouts. Also, this is a common requirement among DISA STIGs and CIS baselines regarding container operation (within Kubernetes environments, but still equally relevant for layered defense in depth). :-)

Additionally important, I add the codebase, just without the `docs` directory to save more space because it's beefy in `/oscal` such that an image can be self-contained. As it stands, a user can use `podman` or `docker` or `docker-compose` with a volume mount (`-v $(pwd):/oscal`) and override the data in the container with that of the local code tree in the directory as well. Flexible for NIST OSCAL development, but more effective for downstream users when they want to forward deploy a container.

I would like to schedule some time to discuss what branches and tags should be released as images, as that is the only part I have not handled. I can, I just want to know the intent and desire of the NIST OSCAL development team. I can then clean up the `push` config and rebase this for a single commit to merge into the repo and not all my fix-up commits.

**Comment by Rene2mt** [comment]
Should we add a step in the github action to scan the container images (e.g., https://github.com/snyk/actions/tree/master/docker)?

**Comment by xee5ch** [comment]
> Should we add a step in the github action to scan the container images (e.g., https://github.com/snyk/actions/tree/master/docker)?

Up to Dave and team, but since it appears Dependabot is in use for language library scanning, perhaps that would be faster and more effective to integrate? [GitHub seems to support it now](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem).

**Comment by xee5ch** [comment]
Also, going to rebase this `release-1.0` to match current guidance.

**Comment by xee5ch** [comment]
After review of this today, we decided that handling vulnerability management and updating libraries should be handled just before publishing the container image for general use.

Pointing back to `main` and not going to rush to merge/publish until those engineering challenges are addressed. :-)

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist, do we want to move this to a feature branch and park it for now, maybe remove the PR until the logistical out-of-band work with container signing occurs and vuln management occurs? I am sure we can guide the community PR accordingly.

Also, this is likely still going to impact and/or block an official container image for `oscal-cli` in https://github.com/usnistgov/oscal-cli/issues/45.

**Comment by aj-stein-nist** [comment]
Closing this for now. NIST staff or the community can reopen PRs as needed later, as this is not currently urgent.

**Pull request closed without merging**
