### PR TITLE
Add OSCAL Content Page

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

This PR adds a page to list official NIST and community-sourced content in OSCAL data formats as part of usnistgov/OSCAL#1294.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist, here is a screenshot of the current draft of the page in the branch.

Screenshot 2022-06-16 at 13-28-52 Content

**Comment by iMichaela** [comment]
@aj-stein-nist -- I still believe that a page like this one that provides links to content others are developing, hosted by NIST, will be perceived as endorsed by NIST with respect to the accurate/correct use of the OSCAL models in generating the content. A simple **declaration** of content validation does not ensure even correct formatting. Considering these concerns, the fact that the NIST team does not have the resources to review the submitted OSCAL content, and because the idea of a community-led task force responsible for reviewing the linked content was poorly received,  **I am against NIST hosting such a page.** It can cause more harm than good IF others are following examples that are not promotting best bractices of using OSCAL. Entities might invest substantial time and funds in implementing security automation processes that are following incorrect examples listed on our website, and NIST will be blamed. I will be for such a page IF someone (not NIST but NIST trusted) assumes the responsibility of reviewing the content before it is listed.

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist -- I still believe that a page like this one that provides links to content others are developing, hosted by NIST, will be perceived as endorsed by NIST with respect to the accurate/correct use of the OSCAL models in generating the content. 

I don't really see this could be different from OSCAL-based tools we list today. We have no guarantees of the tool or the OSCAL data they generate are correct, do we?

That said, I only created the page because it was in the sprint and assigned to me. I don't have a specific philosophical position on the matter. Perhaps we can discuss this further with the team?

**Comment by david-waltermire-nist** [comment]
@iMichaela We have had multiple members of the community ask for a page of this sort and end users asking where they can find sources of OSCAL content. If we don't host something like this, then how should content providers and consumers connect? What is the opportunity cost to OSCAL adoption if they don't connect? I believe there are costs on both sides of the debate.

I believe a disclaimer, such as what we are including on this page and the tools page, addresses concerns around any endorsements. We clearly indicate that we don't endorse the referenced resource or make any statements about its quality. Could we add text to make this more clear?

Regarding your concerns about content authors not following best practices, I share the same concerns, but I don't see how this page would make a significant difference. The content is still out there and the best practices are still being violated regardless of if we point to it. Another way of thinking about this is the more we raise awareness around content, the more the community can self correct when best practices are violated.

**Comment by iMichaela** [comment]
@aj-stein-nist - I agree, and the lessons learned from the OSCAL Tools page are the ones that raised my concerns to this level. Not once I heard ‘the tool X listed on the OSCAL page is not doing x, y, x ‘ or ‘How can I check the tool x is generating valid OSCAL’ . There is though a slight difference: a tool can be tested (maybe) before purchasing or using it with NIST OSCAL content (809-53 and examples) . With OSCAL content, even well formatted one, we saw cases when OSCAL was not used as intended

**Comment by aj-stein-nist** [comment]
Any updates on this PR, @david-waltermire-nist? The issue was closed in Sprint 54 but the page is still in draft and it was never publicized.

**Comment by aj-stein-nist** [comment]
@iMichaela is there any update on the consultation with legal? This PR is associated with an issue that is from long ago, and predates our updated board. So I am going to close this PR for now and put the issue itself in the backlog. Feel free to update with a status though.

**Comment by iMichaela** [comment]
@aj-stein-nist Yes, The legal office recommended we transfer to the community the page with OSCAL Tools and the proposed page with OSCAL Examples generated by non-NIST people. Now that the FY23 started, we hope to make any appropriate arrangements.

**Pull request closed without merging**
