### PR TITLE
Do not require a `protocol/@name` for #1772

### PR DESCRIPTION
**Pull request by aj-stein-gsa**
# Committer Notes

Per discussion with community members and the nature of port, protocol, and service declarations in a OSCAL SSP model instances for RMF use cases, like FedRAMP and others. It would appear the model, per the Metaschema declarations and documentation, require a port range has a name that is commonly the IANA service name, which should be optional. Otherwise, developers and security officials will need to create an arbitrary name that does not strictly conform to the documentation. More details can be found in the issue thread referenced below by URL.

https://github.com/usnistgov/OSCAL/issues/1772#issuecomment-2466441626

This PR may not completely bring #1772 to resolution, but it may be sufficient to close the issue with one possible approach.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~ This repo does not contain model-based/instance-based testing; we will update the GSA FedRAMP Automation Team's test suite accordingly for public review and ongoing use.
- ~Have you included examples of how to use your new feature(s)?~ Not in this repository, but will work with GSA FedRAMP Automation Team to update our constraints and examples accordingly.
- ~ Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.~

### CODE REVIEW

**Comment by wendellpiez** [comment]
As an improvement this almost speaks for itself -- while links are also helpful (thanks @aj-stein-gsa). My concern is only a process concern, namely whether PRs should be targeting `main` or some other branch. (But that's not up to me, while tangled with other questions -- @iMichaela ?)

**Review by iMichaela — CHANGES_REQUESTED** [review]
This is reasonable and agree to move forward with removing the constraint for the protocol name, but I disagree with pushing it to main. The develop branch has a lot of important updates to dependencies and some other backwards compatible fixes that are staged for a patch release. I suggest submitting it against the `develop` branch unless anyone has a major complaint against any staged update.

**Comment by aj-stein-gsa** [comment]
@iMichaela, against the documented guidance and my recommendations, per your request I rebased and this PR now targets develop. I would welcome the following.

1. Enable the GitHub Actions workflow to run the CI/CD actions and validate it is good for merge, post-approval.
2. A review to approve.

**Review by iMichaela — APPROVED** [review]
LGTM

**Pull request merged**
