### PR TITLE
Implement opr:oscal-version function

### PR DESCRIPTION
**Pull request by galtm**
# Committer Notes

This pull request addresses the "Implemented in XSLT profile resolver" part of #1313 and also adds utility functions for working with Semantic Version 2.0.0 strings.

The opr:oscal-version XSLT function meets the "req-meta-oscal-version" requirement
(MUST) from #1386.

The v:compare utility function helps opr:oscal-version meet the
"req-meta-oscalversion-error" requirement.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by galtm** [comment]
@david-waltermire-nist , @wendellpiez : I'm taking this pull request out of draft status because I updated the code that compares version strings to handle pre-release identifiers. Please see version_util.xsl.

**Comment by galtm** [comment]
See also a question I had in https://github.com/usnistgov/OSCAL/discussions/1437.

**Comment by galtm** [comment]
Addresses part of #1440

**Review by david-waltermire-nist — APPROVED** [review]
LGTM. Very well tested! Thanks!

**Pull request merged**
