### PR TITLE
Update presentation for correct component types for #1083.

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

Backport the last leveraged authorization presenation (v6a) in Powerpoint and PDF format to correct inaccuracies.

- `component/@type` was identified as `"leveraged-system"`, not `"system"`.
- `annotation` had been removed at `1.0.0` shortly after this presentation, so this was removed where referenced.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~ (Presentation change)
- ~Have you included examples of how to use your new feature(s)?~ (Presentation change but it includes examples)
- [x] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Review by Compton-NIST — APPROVED** [review]
Marking as approved but @aj-stein-nist you might want to consider updating the date in the presentation to include a "Revised on..." date in case it anyone assumes they have the most up to date version of the ppt/pdf.

**Comment by aj-stein-nist** [comment]
> Marking as approved but @aj-stein-nist you might want to consider updating the date in the presentation to include a "Revised on..." date in case anyone assumes they have the most up to date version of the ppt/pdf.

I am ok to do that but I might need a quick re-review. It should come up in a few minutes.

**Review by iMichaela — DISMISSED** [review]
LGTM

**Comment by aj-stein-nist** [comment]
> > Marking as approved but @aj-stein-nist you might want to consider updating the date in the presentation to include a "Revised on..." date in case anyone assumes they have the most up to date version of the ppt/pdf.
> 
> I am ok to do that but I might need a quick re-review. It should come up in a few minutes.

I was a little late on this and got around to adding the revised line. I will override and merge based on the previous approvals.

**Pull request merged**
