### PR TITLE
Profile resolver compatibility with Saxon 11 (on top of other unmerged PRs)

### PR DESCRIPTION
**Pull request by galtm**
# Committer Notes

This PR addresses issue #1629 by replacing usage of `document-uri` with `base-uri`. The `document-uri` function is known to return different results in Saxon 10 vs. 11. Using `base-uri` removes a difference in the XSLT profile resolver's behavior between Saxon 10 and 11.

This PR builds on top of #1596, which in turn builds on #1549. What's new in this PR is commit 3c96945d4cd6d7b2f6ce45741505f2d9542313ac.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### Testing Done
- Ran all the unit-level XSpec tests (that is, the `.xspec` files in the `testing/` directory) with Oxygen 24.1, which uses Saxon 10.
- Ran all the unit-level XSpec tests with Oxygen 25.0, which uses Saxon 11.
- With both Oxygen 24.1 and 25, transformed all the profiles in `src/specifications/profile-resolution/profile-resolution-examples`. Diff'd the results, and they are the same except time stamps. The profiles that deliberately error out (e.g., `broken_profile.xml`) behave the same way in both Oxygen versions.
- Used the command in the "How do we replicate this issue" section of #1629. Now the command works with Saxon 12.0.

### CODE REVIEW

**Comment by galtm** [comment]
Hi, @aj-stein-nist and @wendellpiez . I mentioned in the description that this PR builds on two earlier unmerged PRs. That seemed like the simplest approach, and it means that end users who want to try out the latest XSLT profile resolver can try it from this branch instead of having to merge code themselves. If you want me to rebase this code differently, let me know.

**Comment by GaryGapinski** [comment]
I tested this (https://github.com/galtm/OSCAL/tree/saxon11) with Saxon-HE v11.5 and v12.0 and my tests succeeded.

**Review by wendellpiez — APPROVED** [review]
Please to accept the PR! Much awesome work here. Going beyond the Saxon compatibility correction it includes more features for exception-handling and tracing as well as more/better tests.

**Review by aj-stein-nist — APPROVED** [review]
First off, thank you very much for taking the time to do this, @galtm. I reviewed and focused on the Saxon 11 compatibility fixes and tests with the specific commit. I had to cherry-pick it to realize it was actually helpful to fix another big that is breaking our pipelines.

To that end, can you please update the PR to back out other changes and only include the https://github.com/usnistgov/OSCAL/commit/3c96945d4cd6d7b2f6ce45741505f2d9542313ac work? I would like to test the feature improvements for profile resolution separate from this bug fix, and it is good we merge this sooner, not later. If you need my help with that or prefer I do it for myself, please let me know. Since it is your branch, I would like to ask for permission first, not forgiveness. :-)

**Review by aj-stein-nist — CHANGES_REQUESTED** [review]
First off, thank you very much for taking the time to do this, @galtm. I reviewed and focused on the Saxon 11 compatibility fixes and tests with the specific commit. I had to cherry-pick it to realize it was actually helpful to fix another big that is breaking our pipelines.

To that end, can you please update the PR to back out other changes and only include the https://github.com/usnistgov/OSCAL/commit/3c96945d4cd6d7b2f6ce45741505f2d9542313ac work? I would like to test the feature improvements for profile resolution separate from this bug fix, and it is good we merge this sooner, not later. If you need my help with that or prefer I do it for myself, please let me know. Since it is your branch, I would like to ask for permission first, not forgiveness. :-)

**Comment by galtm** [comment]
> To that end, can you please update the PR to back out other changes and only include the [3c96945](https://github.com/usnistgov/OSCAL/commit/3c96945d4cd6d7b2f6ce45741505f2d9542313ac) work?

@aj-stein-nist : The `galtm:saxon11-off-develop` [branch](https://github.com/galtm/OSCAL/tree/saxon11-off-develop) has only the Saxon 11 compatibility work, on top of the develop branch's head. You can see the commit here:  https://github.com/galtm/OSCAL/commit/91a12436c82369bad178421255ca411920af2918

The commit on that branch is a little different from commit [3c96945] in this PR, because the work for #1549 and #1596 intersects with the Saxon 11 compatibility changes. I don't want to accidentally lose the updates in the intersecting code as a result of changing this PR, so I'm hesitant to change this PR immediately. Does staging it according to the following plan make sense?

1. I make a new PR from `galtm:saxon11-off-develop`
2. You merge the new PR
3. I push new commits to #1549 and #1596 so that they maintain compatibility with Saxon 11
4. One of us closes this PR (without merging) after we determine that its code is already part of the other PRs

**Comment by wendellpiez** [comment]
I have already explained to AJ that it's my fault the stuff is all together. Planning for the wrong contingency.

**Comment by galtm** [comment]
> I have already explained to AJ that it's my fault the stuff is all together. Planning for the wrong contingency.

No worries. I don't see it as your fault and I don't think it even matters. We'll move forward in some fashion and get where we need to be.

**Comment by galtm** [comment]
> That plan is fine by me,

OK, great. I will redo the testing on the other branch before I make the new pull request, just to make sure. Look for the new pull request in the next couple of days.

**Comment by aj-stein-nist** [comment]
OK, @galtm, are we good to close this one in favor of #1685 and track the other feature PRs after a rebase? I do not want to lose track of your efforts. Thanks for working with us as I had asked.

**Comment by galtm** [comment]
> OK, @galtm, are we good to close this one in favor of #1685 and track the other feature PRs after a rebase? I do not want to lose track of your efforts. Thanks for working with us as I had asked.

@aj-stein-nist , yes, this pull request can be closed without merging it. I'll update the other two PRs to bring them up to date with #1685.

**Comment by galtm** [comment]
> I'll update the other two PRs to bring them up to date with #1685.

Done!

**Pull request closed without merging**
