### PR TITLE
Remove content artifacts moved to new content repo

### PR DESCRIPTION
**Pull request by david-waltermire-nist**
# Committer Notes

Remove all content artifacts from the main OSCAL repo, since these have been moved to the [OSCAL content repo](https://github.com/usnistgov/oscal-content). Also update all references to this content to point to the new repo, and add README.md files in old content locations to point to the new locations.

Also updated the Lunch with the Devs and Model review meeting entries to post the latest slides and info,.

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by david-waltermire-nist** [comment]
All of the changes to remove the content from the main OSCAL repo are done in the PR. I updated all existing README.md files in the `content` and `src\content` directories to have pointers to the new repo. Please review and let me know if you want any changes.

**Comment by iMichaela** [comment]
Will review the PR tomorrow afternoon (9/1/2020)

**Comment by david-waltermire-nist** [comment]
@iMichaela I completed the edits to address your feedback. [These are the changes](https://github.com/david-waltermire-nist/OSCAL/compare/805d5f6..8e40748) since your last review.

I also added some updates for the model review and dev lunch meetings.

Can you review this diff and approve the review?

**Review by iMichaela — APPROVED** [review]
Everything looks great now. Thank you.

**Comment by isimluk** [comment]
:clap:

**Pull request merged**
