### PR TITLE
Add possible Schematron documentation checks

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

This is the product of the meeting and spike where we pair-programmed and came up with example Schematron rules for tentative editorial standards that can be used for reviews of models and embedded docs as part of usnistgov/OSCAL#801.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- ~Have you added an explanation of what your changes do and why you'd like us to include them?~
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.~

### CODE REVIEW

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist This needs to be rebased.

**Review by david-waltermire-nist — CHANGES_REQUESTED** [review]
I am good with adding these checks, but they need to be integrated into the CI. Please add this to the CI.

**Comment by aj-stein-nist** [comment]
> I am good with adding these checks, but they need to be integrated into the CI. Please add this to the CI.

Will do, sir!

**Comment by aj-stein-nist** [comment]
> I am good with adding these checks, but they need to be integrated into the CI. Please add this to the CI.


Dave, I am going to push up just a few changes to the SSP metaschema def and imported common modules metaschema def(s) for the SSP. This shows the CI/CD checker in action with the amended script to run the checks in CI/CD.

https://github.com/usnistgov/OSCAL/actions/runs/3364015177/jobs/5577876131

The commit after this ought to resolve them. The other build failures are blocked until we merge the URI and link check PRs currently out for review.

**Comment by aj-stein-nist** [comment]
Rebased and ready to review.

**Review by david-waltermire-nist — CHANGES_REQUESTED** [review]
We should merge the documentation check into the composition check schematron, since all inherited schematrons will be checked as well.

**Comment by aj-stein-nist** [comment]
> We should merge the documentation check into the composition check schematron, since all inherited schematrons will be checked as well.

Sounds good, I can make those changes accordingly!

**Comment by aj-stein-nist** [comment]
> > We should merge the documentation check into the composition check schematron, since all inherited schematrons will be checked as well.
> 
> Sounds good, I can make those changes accordingly!

Oh on second thought, I guess this means I need a Metaschema repo PR first, as that is where the Metaschema composition check is housed. I will refactor this and move the Schematron accordingly into the existing one, and just call it in CI/CD scripting. I will revert the `validate-metaschema.sh` file changes accordingly.

**Comment by aj-stein-nist** [comment]
Changes made and https://github.com/usnistgov/metaschema/pull/246 opened.

**Review by david-waltermire-nist — DISMISSED** [review]

**Review by david-waltermire-nist — APPROVED** [review]
Thanks!

**Pull request merged**
