### PR TITLE
Update automation to centralized triage board

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

The old board (https://github.com/usnistgov/OSCAL/projects/52) has been deprecated and it is time to switch board automation. Repo admins will get emails on every triage automation failure as old board is closed. There is no attached issue as this work is helpful to ensure there is a limited gap in triage board coverage as we finish the initial migration from the old per-project boards.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~ N/A
- ~Have you included examples of how to use your new feature(s)?~ N/A
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.~ N/A

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
May need to set up a test board tomorrow afternoon on my fork to confirm it is working before converting from draft to ready PR for team review.

**Comment by aj-stein-nist** [comment]
As linked with [a test repository](https://github.com/ImportantFederalAgencyTest/test-project-integration-repo/actions), it appears very important to the one official action set up for this purpose, made by GitHub themselves, and the underlying GraphQL API that it is a strong requirement the account (in this case, [oscalbuilder service account](https://github.com/oscalbuilder) be a member of the usnistgov org. For the projects workflow, automatic addition by filter can only work with one repo given the usnistgov org payment plan, so getting GitHub Actions to work is necessary and will vastly reduce tool regarding automated management of the board. Will talk to the NIST team that manages GitHub tomorrow morning or before end of this week if we can determine how to do that, and if so moved forward.

For the time, being, I will mark this as blocked. I thought this would be quick, but foiled once again by permissions. 😢

**Comment by aj-stein-nist** [comment]
Also of note that the action, made by GitHub developers, must use a PAT (classic token, not beta fine-grained at the time of this writing) and new tokens must have `public_repo` and full `project` scopes (not `read:project` only) for this to work based on yesterday's testing. Screenshot of updated PAT below.

image

**Review by nikitawootten-nist — APPROVED** [review]

**Comment by nikitawootten-nist** [comment]
@aj-stein-nist should we replicate this workflow across the other OSCAL-umbrella repositories? If so, do the needed `COMMIT_TOKEN` permissions exist for each of them? (`-Pages`, `-Reference`, -`-content`, `-xslt`?)

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist should we replicate this workflow across the other OSCAL-umbrella repositories? If so, do the needed `COMMIT_TOKEN` permissions exist for each of them? (`-Pages`, `-Reference`, -`-content`, `-xslt`?)

That was my intent for [only the core projects for now](https://pages.nist.gov/OSCAL/about/projects/). Are you volunteering to help? (Tokens were adjusted this morning, just need to send out PRs. 😎)

**Comment by iMichaela** [comment]
@aj-stein-nist and team - do we want to have it further discussed and have the team trained tomorrow during our lunch and learn, unless there is no other topic more important.

**Pull request merged**
