### PR TITLE
Removed references to PM-33

### PR DESCRIPTION
**Pull request by egyptiankarim**
It looks like updates to the Privacy baselines didn't remove references to the deleted PM-33 control.

# Committer Notes

The PM-33 control is not in the final version of 800-53 Rev5, and it looks like references were appropriately deleted across most of the OSCAL content; however, I found a few lingering ones in the Privacy baselines. 

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by iMichaela** [comment]
@egyptiankarim The final OSCAL baselines (based on SP 800-53B final document) have not been posted. The *FPD* baselines are the "Final Public Draft" baselines and not the final ones. They will have to stay accurate to what the FPD SP800-53B document was listing when published. Sorry for the confusion.

**Review by iMichaela — COMMENTED** [review]
The final OSCAL baselines (based on SP 800-53B final document) have not been posted. The FPD baselines are the "Final Public Draft" baselines and not the final ones. They will have to stay accurate to what the FPD SP800-53B document was listing when published.

**Comment by david-waltermire-nist** [comment]
We are working on a [PR](https://github.com/usnistgov/oscal-content/pull/32) that will update the OSCAL catalog and profiles for SP 800-53 rev 5 and SP 800-53B. This issue will be fixed by that PR.

**Comment by egyptiankarim** [comment]
@iMichaela @david-waltermire-nist Sounds good! Thanks for the information!

**Comment by david-waltermire-nist** [comment]
PR #32 has been merged. This issue can be closed.

**Pull request closed without merging**
