### PR TITLE
Flatten codeowners

### PR DESCRIPTION
**Pull request by nikitawootten-nist**
# Committer Notes

Codeowners file now defaults to `@usnistgov/itl-oscal-maintainers`.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Review by iMichaela — CHANGES_REQUESTED** [review]
@nikitawootten-nist  
-- 1)  it turns out that @Compton-NIST is not a member of the usnitgov/itl-oscal, and I cannot fix it because @aj-stein-nist is the maintainer.  We should also review all the other usnistgov/its-oscal-*  teams and update them.  
-- 2) maybe some (critical) directories should remain protected and only its-oscal-admins should own the code in those directories currently owned by its-oscal-maintainers which does not even exist among usnistgov teams.

**Comment by aj-stein-nist** [comment]
> @nikitawootten-nist -- 1) it turns out that @Compton-NIST is not a member of the `usnitgov/itl-oscal`, and I cannot fix it because @aj-stein-nist is the maintainer. We should also review all the other `usnistgov/its-oscal-*` teams and update them.

I just saw this update. You @iMichaela were added to the maintainer list and I removed myself.

> -- 2) maybe some (critical) directories should remain protected and only `its-oscal-admins` should own the code in those directories currently owned by `its-oscal-maintainers` which does not even exist among `usnistgov` teams.

You have to be logged in for itl-oscal-maintainers as it is a private group, or otherwise you will not see or you are logged in and you are not a member. For you that problem should now be solved. Let me know if you need anything else.

**Comment by iMichaela** [comment]
> You have to be logged in for itl-oscal-maintainers as it is a private group, or otherwise you will not see or you are logged in and you are not a member. For you that problem should now be solved. Let me know if you need anything else.

Thank you, @aj-stein-nist , for updating the roles.  I'll work with @nikitawootten-nist  on the -- 1) , second part.

**Review by iMichaela — APPROVED** [review]
LGTM. The system reports an error because 2 groups (out of three used) are not public. The groups exist  and have access to the repo. The fact that the 2 groups are not public might not be a problem (we operated this way before).

**Pull request merged**
