### PR TITLE
Extension model

### PR DESCRIPTION
**Pull request by brian-ruf**
# Committer Notes

This is a functional draft of the OSCAL Extensions Model.

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by david-waltermire-nist** [comment]
@brianrufgsa Can you post the updated commits to fix the broken links?

**Comment by brianrufgsa** [comment]
@david-waltermire-nist They are in PR #824 
If you process that one, I can rebase and re-push this one.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa I merged #824. Can you rebase?

**Comment by iMichaela** [comment]
@brianrufgsa and @david-waltermire-nist Is there any documentation for the OSCAL Extensions Model?

**Comment by iMichaela** [comment]
@gregelin, @aaronlippold or @ohsh6o - can you also please take a look at the Extension Model through the lens of the InSpec integration you are trying to do? Any feedback is appreciated. Thank you.

**Comment by gregelin** [comment]
Will take a look this evening.

Greg Elin
CEO, GovReady PBC
p: 917-304-3488
e: gregelin@govready.com

Sent via Superhuman ( https://sprh.mn/?vip=gregelin@govready.com )

**Comment by brianrufgsa** [comment]
@gregelin here is an example of the model in use.
https://github.com/brianrufgsa/fedramp-automation/blob/sap-sar-rc1/src/resources/xml/FedRAMP_extensions.xml

**Comment by ohsh6o** [comment]
@brianrufgsa I was asking about this stuff with/on behalf of the guilty parties because I am trying too figure out where I am trying to insert mapping data. More to come over the next day or so as I have examples and more directed questions.

To start, how are you generating the XML->JSON outputs of that extension? I see it is not part of the CI/CD process upstream, so I presume you are invoking the Extension Metaschema definition on the XML version of this file to output the JSON version?

**Comment by brianrufgsa** [comment]
@ohsh60 I used the generate-converters.sh script from the CI/CD pipeline to generate the converter for this metaschema, then I used it to convert the XML to JSON so I could publish both versions.

**Pull request closed without merging**
