### PR TITLE
Rename `.github/README.md` file to `ABOUT.md`

### PR DESCRIPTION
**Pull request by guyzyl**
# Committer Notes

Currently, when opening the OSCAL repo on GitHub, the `README.md` that is shown is take from `./.github/README.md` instead of `./README.md`.
This is a documented behavior of GitHub which can be seen [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes).

To make the repo better documented, I renamed the `.github/README.md` file to `ABOUT.md` so the real (and main) `README.md` file would be shown when opening the repo on GitHub.
(I also added a missing newline to the end of the file on the way to conform to markdown conventions)

This is a small change that will majorly improve the repo's GitHub page, and I opend the PR to `main` branch on purpose so the changes would be reflected ASAP.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### CODE REVIEW

**Review by aj-stein-nist — APPROVED** [review]
Also a nice catch. Not sure how I (or other missed this), despite opening the repo dozens of times a day. I guess scrolling is important. Thanks for doing this!

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist, this one we might want to merge sooner rather than later since the main README is hidden, I hadn't notice as a consequence of merging usnistgov/OSCAL#1157 yesterday.

**Comment by guyzyl** [comment]
@aj-stein-nist np 🙂

**Review by david-waltermire-nist — APPROVED** [review]
Thanks a bunch!

**Pull request merged**
