### PR TITLE
Hotfix/refactor duplicates

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

naming conflicts in the metaschema cause errors in java model generation. this refactoring of models allows for validation use the metaschema validate-content command to correctly run

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by aj-stein-gsa** [comment]
This may not be need and is related to a bug in the behavior of metaschema-java not conforming to the Metaschema spec and processiong behavior for two independent inline assembly definitions still being independent despite the same identical local name. See https://github.com/metaschema-framework/metaschema-java/issues/259 for more details.

**Comment by wandmagic** [comment]
> This may not be need and is related to a bug in the behavior of metaschema-java not conforming to the Metaschema spec and processiong behavior for two independent inline assembly definitions still being independent despite the same identical local name. See [metaschema-framework/metaschema-java#259](https://github.com/metaschema-framework/metaschema-java/issues/259) for more details.

it may not be needed but it will also improve type generation and json-schema quality downstream, by re-using two seperate duplicate definitions which define the same thing

**Review by iMichaela — CHANGES_REQUESTED** [review]
These are unacceptable changes as proposed . 
1) NIST does not accept schemas not developed by NIST (see https://raw.githubusercontent.com/metaschema-framework/metaschema/refs/heads/develop/schema/xml/metaschema.xsd">)
2) The extend of proposed changes is not justified by the implied hotfix for a pair of clashing constraints

**Comment by wandmagic** [comment]
> These are unacceptable changes as proposed .
> 
> 1. NIST does not accept schemas not developed by NIST (see [https://raw.githubusercontent.com/metaschema-framework/metaschema/refs/heads/develop/schema/xml/metaschema.xsd">](https://raw.githubusercontent.com/metaschema-framework/metaschema/refs/heads/develop/schema/xml/metaschema.xsd%22%3E))
> 2. The extend of proposed changes is not justified by the implied hotfix for a pair of clashing constraints

rolled the schema change back, the schema change is not needed for the hotfix

**Comment by wandmagic** [comment]
Closing, this, we can fix these issues upstream in metaschema java

**Pull request closed without merging**
