### PR TITLE
Profile resolver: Metadata tests and way of determining top UUID

### PR DESCRIPTION
**Pull request by galtm**
# Committer Notes

This pull request adds XSpec tests for the profile resolver's metadata phase and also includes minor updates in the XSLT, mostly to align with latest profile resolver spec.

- Remove global parameter assign-uuid (note backward incompatibility - is it OK?)
- Instead, support global parameters uuid-method and top-uuid, in uuid-method-choice.xsl
- Support global parameter hide-source-profile-uri
- Stub of opr:oscal-version function
- Stub of message handler template, using xsl:message for now
- Add XSpec tests

### All Submissions:

- [x] Have you selected the correct base branch per  [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

I don't think my XSLT updates are changes in core features, but let me know if they are.

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by wendellpiez** [comment]
Created #1178 to amend readmes at top level, which now require revision. Formerly, the Profile Resolver was used primarily in CI/CD and had simple entry points with no parameters. Now it supports runtime flags, we also need to write the documentation.

**Review by wendellpiez — DISMISSED** [review]
Made #1178 as follow-on

**Comment by david-waltermire-nist** [comment]
@wendellpiez and @galtm Should we address #1178 before merging this? This could be done as a PR against or update to @galtm 's branch.

**Comment by wendellpiez** [comment]
Sure, @galtm what makes sense to you? It's easy enough for me to make a PR using Github alone for this task. Alternatively if you know what you need to know, it would likely be easy to fold in.

**Comment by galtm** [comment]
@wendellpiez  and @david-waltermire-nist , are you asking if I can do #1178? I don't mind updating a readme. I have two questions, though.

1. I noticed that 1178 says it is for v1.0.3, but I assumed this PR would be for a later version. If I mention the runtime flags as in this PR, should I do that on the develop branch and then 1178 is not really for v1.0.3?

2. Is there more than one readme about the profile resolver? The one I see is https://github.com/usnistgov/OSCAL/blob/main/src/utils/util/resolver-pipeline/readme.md.

**Comment by wendellpiez** [comment]
@galtm it looks likely to me #1178 is mislabelled and it should be 1.1.0 - @david-waltermire-nist ?

As for which readme, how about updating the one you see, which pertains specifically to how to operate this pipeline, and give us a heads-up if you see anything amiss or wrong in any of the others? We could track loose ends on the Issue and either make edits accordingly or spin off new Issues.

**Comment by galtm** [comment]
I pushed 0d0c508f0b072a8cc2cec02893ad39a2e1322282 to address #1178 . Also,

- I clarified what is in the testing subfolder.
- I made some editorial-type updates that I hope are enhancements.
- Based on a conversation with @wendellpiez , I changed `$home` from a global XSLT parameter (settable when invoking the pipeline) to a global XSLT variable because we didn't think the value needed to be settable from the outside.

@wendellpiez and @david-waltermire-nist : Let me know if you want to iterate on the readme or if there's anything else I should do for this PR.

**Review by wendellpiez — APPROVED** [review]
Awesome! thanks @galtm

**Review by david-waltermire-nist — APPROVED** [review]
Thanks Amanda!

**Pull request merged**
