### PR TITLE
Update metaschema for 1.0.6 release

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

This PR commit will update the Metaschema submodule to update. We need to update the underlying version of the MIMF to address the following:

Closes usnistgov/OSCAL#1773.
Closes usnistgov/OSCAL#1774.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
Re [test failures in this workflow run](https://github.com/usnistgov/OSCAL/actions/runs/5394407864/jobs/9795529935?pr=1820) it is checking the now defunct [GSA FedRAMP Automation repo baseline URL](https://github.com/GSA/fedramp-automation/tree/master/dist/content/baselines) that has been addressed in develop or main a while ago, I don't want to expend effort cherry-picking that commit and causing problems later on as we merge main and rebase develop soon enough.

**Review by wendellpiez — APPROVED** [review]
Record number of contributors for us I think? 👍

**Comment by aj-stein-nist** [comment]
Just a note the force-push on this PR was to switch to [the tagged commit of the newly minted 0.9.0 released that officially dropped this afternoon](https://github.com/usnistgov/metaschema/releases/tag/v0.9.0). The only resulting change that was not officially in yet is the JSON schemas allow you to bind to an OSCAL JSON schema into an example document, but testing review and release will commence tomorrow as planned.

**Review by Compton-NIST — APPROVED** [review]

**Review by nikitawootten-nist — CHANGES_REQUESTED** [review]
EDIT: this is not the only broken link. Some are in the downstream metaschema repo (not worth in this release, but a small bug report or nudge in a future metaschema PR should do it)

---

# `/build/ci-cd/README.md`

As reported by the markdown link check, the readme `/build/ci-cd/README.md` uses the old path to the metaschema schema.

Please update line 51 from:
```
1. [validate-metaschema.sh](validate-metaschema.sh): Ensures that all [metaschema](https://github.com/usnistgov/OSCAL/tree/master/src/metaschema) are valid according to the [metaschema XML schema](https://github.com/usnistgov/metaschema/blob/master/toolchains/xslt-M4/validate/metaschema.xsd).
```

to:
```
1. [validate-metaschema.sh](validate-metaschema.sh): Ensures that all [metaschema](https://github.com/usnistgov/OSCAL/tree/master/src/metaschema) are valid according to the [metaschema XML schema](https://github.com/usnistgov/metaschema/blob/master/schema/xml/metaschema.xsd).
```

(this change is related to the metaschema-xslt migration which will eventually rip out everything from the `/toolchains` directory)

**Comment by aj-stein-nist** [comment]
> EDIT: this is not the only broken link. Some are in the downstream metaschema repo (not worth in this release, but a small bug report or nudge in a future metaschema PR should do it)
> # `/build/ci-cd/README.md`
> 
> As reported by the markdown link check, the readme `/build/ci-cd/README.md` uses the old path to the metaschema schema.
> 
> Please update line 51 from:
> 
> ```
> 1. [validate-metaschema.sh](validate-metaschema.sh): Ensures that all [metaschema](https://github.com/usnistgov/OSCAL/tree/master/src/metaschema) are valid according to the [metaschema XML schema](https://github.com/usnistgov/metaschema/blob/master/toolchains/xslt-M4/validate/metaschema.xsd).
> ```
> 
> to:
> 
> ```
> 1. [validate-metaschema.sh](validate-metaschema.sh): Ensures that all [metaschema](https://github.com/usnistgov/OSCAL/tree/master/src/metaschema) are valid according to the [metaschema XML schema](https://github.com/usnistgov/metaschema/blob/master/schema/xml/metaschema.xsd).
> ```
> 
> (this change is related to the metaschema-xslt migration which will eventually rip out everything from the `/toolchains` directory)

Nikita and others looked at this during pairing session to prep release, we would need to change the grep syntax to quickly exclude specific directories from the markdown-link-checker scan uses null-terminated lists of file paths from git and uses [an inverse match to exclude them](https://github.com/usnistgov/OSCAL/blob/2f888c7656574d5ad223def3576027bf74138265/.github/workflows/workflow-validate-repo-markdown.yml#L52-L61) based on [the GHA workflow input](https://github.com/usnistgov/OSCAL/blob/2f888c7656574d5ad223def3576027bf74138265/.github/workflows/workflow-validate-repo-markdown.yml#L5-L9). Will need to figure out a way to address this *maybe* as a lot of these path changes will go away with repo restructuring and/or upcoming usnistgov/metaschema updates.

**Pull request merged**
