### PR TITLE
Profile resolver: Test modify phase, plus minor XSLT enhancements

### PR DESCRIPTION
**Pull request by galtm**
# Committer Notes

This pull request adds template- and function-level XSpec tests for the XSLT profile resolver. It also updates the underlying XSLT, mostly to align with the latest specification.

XSLT
- Warn if set-parameter matches nothing
- Handle more types of children of param
- Make match="control" template handle both implicit and explicit binding
- New oscal:patches-to-id-targeting-ancestor function for processing
  needed in multiple places
- For explicit binding that adds a title, add it after original title
  to facilitate keeping the right one in finish phase
- For removal by class, expect exact match with no tokenization or
  case insensitivity
- In finish phase, keep only last title of a control

XSpec
- Add tests at the level of individual templates and functions

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by galtm** [comment]
Hi @david-waltermire-nist , The validate-website check failed and the log says, "Error: Link checker detected broken or invalid links, read attached report." However, I don't see an attached report. Can you please help me fix this failure? Thanks!

**Comment by aj-stein-nist** [comment]
> Hi @david-waltermire-nist , The validate-website check failed and the log says, "Error: Link checker detected broken or invalid links, read attached report." However, I don't see an attached report. Can you please help me fix this failure? Thanks!

I think you're good for now.

Be sure to click the [Details](https://github.com/usnistgov/OSCAL/actions/runs/2525220441) on the validate-website job check on this PR and click the Summary button in the upper left-hand corner. Scroll all the way to the bottom of this page and locate [the `html_link_report`](https://github.com/usnistgov/OSCAL/suites/6998055384/artifacts/289406757). It had expired, so I just re-ran it for you.

I am not sure what Dave wants us to do here, since we fixed this particular website link in a fix to main in https://github.com/usnistgov/OSCAL/commit/a9f5b5060a2d3d3e0b4c0732b61a0baa856404ce. I think we need to merge `main` back into `develop` accordingly.

**Comment by galtm** [comment]
> I think you're good for now.
> 
> Be sure to click the [Details](https://github.com/usnistgov/OSCAL/actions/runs/2525220441) on the validate-website job check on this PR and click the Summary button in the upper left-hand corner. Scroll all the way to the bottom of this page and locate [the `html_link_report`](https://github.com/usnistgov/OSCAL/suites/6998055384/artifacts/289406757). It had expired, so I just re-ran it for you.

@aj-stein-nist , thank you! Now I'll know how to find future reports. I'll leave it to @david-waltermire-nist to either merge a link fix into `develop` or give me instructions.

**Comment by wendellpiez** [comment]
@aj-stein-nist is this PR getting caught up in that link checker thing we were talking about?

**Comment by david-waltermire-nist** [comment]
@galtm I fixed the broken link. This PR should be completely ready for review.

**Review by wendellpiez — DISMISSED** [review]
Nice work! unit tests too.

**Review by david-waltermire-nist — APPROVED** [review]
Thanks!

**Review by david-waltermire-nist — APPROVED** [review]
LGTM. I rebased this. Thanks!

**Pull request merged**
